# Generated by Django 3.2.13 on 2022-07-11 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0018_alter_project_control_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='labelling_function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the Labelling Function', max_length=60)),
                ('label', models.CharField(help_text='Label Attributed for the Labelling Function', max_length=60)),
                ('type', models.CharField(choices=[('single_regex', 'first match of a regex pattern'), ('regex_matches', 'all matches of a regex pattern'), ('string_match', 'first match of a substring'), ('string_matches', 'all matches of a substring'), ('keywords_searcher', 'all matches of a list of keywords')], default='single_regex', max_length=60)),
                ('content', models.TextField(default='Insert content here', help_text='Searched Word or RegEx expression to match - in Text corresponding to selected label', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a labelling function was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a labelling function was updated', verbose_name='updated at')),
                ('project', models.ForeignKey(help_text='Project ID where the Labelling Function is created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project')),
            ],
        ),
    ]
