# Generated by Django 3.2.13 on 2022-08-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lfmetric',
            name='function',
            field=models.ForeignKey(help_text='labelling function ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='weak_supervision.labelling_function'),
        ),
    ]
