# Generated by Django 3.2.13 on 2022-07-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20220711_1236'),
        ('projects', '0018_alter_project_control_weights'),
        ('weak_supervision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='weak_annotation_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spacy_doc', models.JSONField(default=None, help_text='SpaCy doc file relative to each Task in JSON Format', verbose_name='doc')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a spacy model was run', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a spacy annotation was updated (added spans)', verbose_name='updated at')),
                ('project', models.ForeignKey(help_text='Project ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task', models.ForeignKey(help_text='Corresponding task for this annotation', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
