# Generated by Django 3.2.13 on 2022-07-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_control_weights'),
        ('tasks', '0025_auto_20220711_1236'),
        ('weak_supervision', '0002_weak_annotation_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weak_annotation_logs',
            name='task',
            field=models.ForeignKey(help_text='Task ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0, help_text='start position of entity', verbose_name='start position')),
                ('end', models.IntegerField(default=0, help_text='end position of entitiy', verbose_name='end_position')),
                ('content', models.TextField(default=None, help_text='text of the entity')),
                ('label', models.CharField(help_text='label of the entity', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a labelling function is applied', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a function annotation was updated', verbose_name='updated at')),
                ('function', models.ForeignKey(help_text='labelling function ID', on_delete=django.db.models.deletion.CASCADE, to='weak_supervision.labelling_function')),
                ('project', models.ForeignKey(help_text='Project ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task', models.ForeignKey(help_text='Task ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
