# Generated by Django 3.2.13 on 2022-08-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0002_alter_lfmetric_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregation_model',
            name='conflicts',
            field=models.FloatField(default=0.0, help_text='agg model Conflict score', null=True, verbose_name='conflict'),
        ),
        migrations.AlterField(
            model_name='aggregation_model',
            name='coverage',
            field=models.FloatField(default=0.0, help_text='agg model Coverage score', null=True, verbose_name='coverage'),
        ),
        migrations.AlterField(
            model_name='aggregation_model',
            name='f1_score',
            field=models.FloatField(default=0.0, help_text='agg model F_score score', null=True, verbose_name='f1_score'),
        ),
        migrations.AlterField(
            model_name='aggregation_model',
            name='overlaps',
            field=models.FloatField(default=0.0, help_text='agg model Overlap score', null=True, verbose_name='overlap'),
        ),
        migrations.AlterField(
            model_name='aggregation_model',
            name='precision',
            field=models.FloatField(default=0.0, help_text='agg model Precision score', null=True, verbose_name='precision'),
        ),
        migrations.AlterField(
            model_name='aggregation_model',
            name='recall',
            field=models.FloatField(default=0.0, help_text='agg model Recall score', null=True, verbose_name='recall'),
        ),
        migrations.AlterField(
            model_name='lfmetric',
            name='conflicts',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='lfmetric',
            name='coverage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='lfmetric',
            name='f1_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='lfmetric',
            name='overlaps',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='lfmetric',
            name='precision',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='lfmetric',
            name='recall',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='lfmetric',
            name='results',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
