# Generated by Django 3.2.13 on 2022-07-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0003_auto_20220712_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='content',
        ),
        migrations.AddField(
            model_name='results',
            name='text',
            field=models.TextField(help_text='text of the entity', null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='end',
            field=models.IntegerField(help_text='end position of entitiy', null=True, verbose_name='end_position'),
        ),
        migrations.AlterField(
            model_name='results',
            name='label',
            field=models.CharField(help_text='label of the entity', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='start',
            field=models.IntegerField(help_text='start position of entity', null=True, verbose_name='start position'),
        ),
    ]
