# Generated by Django 3.2.13 on 2022-08-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0003_auto_20220816_1252'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lfmetric',
            constraint=models.UniqueConstraint(fields=('function', 'label'), name='function-label'),
        ),
    ]
