# Generated by Django 3.2.13 on 2022-07-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20220711_1236'),
        ('projects', '0018_alter_project_control_weights'),
        ('weak_supervision', '0004_auto_20220712_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='weak_annotation_logs',
            name='text',
            field=models.TextField(default='', help_text='Corresponding text', null=True),
        ),
        migrations.CreateModel(
            name='aggregate_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='name of the Aggregation model', max_length=60)),
                ('model_type', models.CharField(choices=[('HMM', 'hidden markov model'), ('Majority Voting', 'Majroity Voting')], max_length=60)),
                ('start', models.IntegerField(help_text='start position of entity', null=True, verbose_name='start position')),
                ('end', models.IntegerField(help_text='end position of entitiy', null=True, verbose_name='end_position')),
                ('text', models.TextField(help_text='text of the entity', null=True)),
                ('label', models.CharField(help_text='label of the entity', max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a labelling function is applied', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a function annotation was updated', verbose_name='updated at')),
                ('project', models.ForeignKey(help_text='Project ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task', models.ForeignKey(help_text='Task ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
