# Generated by Django 3.2.13 on 2022-07-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20220711_1236'),
        ('projects', '0018_alter_project_control_weights'),
        ('weak_supervision', '0005_auto_20220718_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='weak_annotation_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, help_text='Corresponding text', null=True)),
                ('spacy_doc', models.JSONField(default=None, help_text='SpaCy doc file relative to each Task in JSON Format', verbose_name='doc')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a spacy model was run', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a spacy annotation was updated (added spans)', verbose_name='updated at')),
                ('project', models.ForeignKey(help_text='Project ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task', models.ForeignKey(help_text='Task ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.RenameModel(
            old_name='aggregate_results',
            new_name='aggregate_result',
        ),
        migrations.RenameModel(
            old_name='metrics',
            new_name='metric',
        ),
        migrations.RenameModel(
            old_name='results',
            new_name='result',
        ),
        migrations.DeleteModel(
            name='weak_annotation_logs',
        ),
    ]
