# Generated by Django 3.2.13 on 2022-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0006_auto_20220718_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='model_version',
            field=models.TextField(null=True, verbose_name='labeling_function'),
        ),
        migrations.AddField(
            model_name='result',
            name='result',
            field=models.TextField(null=True, verbose_name='result'),
        ),
    ]
