# Generated by Django 3.2.13 on 2022-07-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0007_auto_20220718_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregate_result',
            old_name='text',
            new_name='annotation',
        ),
        migrations.RemoveField(
            model_name='aggregate_result',
            name='end',
        ),
        migrations.RemoveField(
            model_name='aggregate_result',
            name='label',
        ),
        migrations.RemoveField(
            model_name='aggregate_result',
            name='start',
        ),
    ]
