# Generated by Django 3.2.13 on 2022-08-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0007_regx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regx',
            name='upload_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
