# Generated by Django 3.2.13 on 2022-07-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0008_auto_20220718_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='conflicts',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='f1_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='function',
            field=models.ForeignKey(help_text='labelling function ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='weak_supervision.labelling_function'),
        ),
        migrations.AddField(
            model_name='metric',
            name='label',
            field=models.CharField(help_text='label of the entity', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='overlaps',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='precision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='recall',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='results',
            field=models.IntegerField(null=True),
        ),
    ]
