# Generated by Django 3.2.13 on 2022-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0009_alter_regx_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazetteersLF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('label', models.CharField(help_text='Label Attributed for the Labelling Function', max_length=60)),
                ('upload_file', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='regx',
        ),
    ]
