# Generated by Django 3.2.13 on 2022-07-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_control_weights'),
        ('weak_supervision', '0009_auto_20220719_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='project',
            field=models.ForeignKey(help_text='Project ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
