# Generated by Django 3.2.13 on 2022-07-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0010_metric_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='model',
            field=models.ForeignKey(help_text='model ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='weak_supervision.aggregate_result'),
        ),
    ]
