# Generated by Django 3.2.13 on 2022-07-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_control_weights'),
        ('weak_supervision', '0011_metric_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='aggregation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='name of the Aggregation model', max_length=60)),
                ('model_type', models.CharField(choices=[('HMM', 'hidden markov model'), ('Majority Voting', 'Majroity Voting')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a labelling function is applied', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a function annotation was updated', verbose_name='updated at')),
                ('project', models.ForeignKey(help_text='Project ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
