# Generated by Django 3.2.13 on 2022-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0011_labelling_function_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelling_function',
            name='type',
            field=models.IntegerField(choices=[(1, 'all matches of one or a list of keywords'), (2, 'all matches of a regex pattern'), (3, 'all matches of a regex pattern'), (4, 'a script of a python function')], default=None),
        ),
    ]
