# Generated by Django 3.2.13 on 2022-08-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0012_alter_labelling_function_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelling_function',
            old_name='file_upload',
            new_name='file_path',
        ),
    ]
