# Generated by Django 3.2.13 on 2022-07-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0012_aggregation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='model',
            field=models.ForeignKey(help_text='model ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='weak_supervision.aggregation_model'),
        ),
    ]
