# Generated by Django 3.2.13 on 2022-07-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_control_weights'),
        ('tasks', '0025_auto_20220711_1236'),
        ('weak_supervision', '0013_alter_metric_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='weak_annotation_log',
            new_name='datadoc',
        ),
    ]
