# Generated by Django 3.2.13 on 2022-08-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0013_rename_file_upload_labelling_function_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GazetteersLF',
        ),
    ]
