# Generated by Django 3.2.13 on 2022-07-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0014_rename_weak_annotation_log_datadoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='end',
        ),
        migrations.RemoveField(
            model_name='result',
            name='start',
        ),
        migrations.RemoveField(
            model_name='result',
            name='text',
        ),
        migrations.AlterField(
            model_name='labelling_function',
            name='content',
            field=models.TextField(default='', help_text='Searched Word or RegEx expression to match - in Text corresponding to selected label', null=True),
        ),
        migrations.AlterField(
            model_name='labelling_function',
            name='type',
            field=models.CharField(choices=[('single_regex', 'first match of a regex pattern'), ('regex_matches', 'all matches of a regex pattern'), ('string_match', 'first match of a substring'), ('string_matches', 'all matches of a substring'), ('keywords_searcher', 'all matches of a list of keywords'), ('python_code', 'a script of a python function')], default='single_regex', max_length=60),
        ),
    ]
