# Generated by Django 3.2.13 on 2022-07-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20220711_1236'),
        ('weak_supervision', '0015_auto_20220727_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadoc',
            name='task',
            field=models.ForeignKey(help_text='Task ID', on_delete=django.db.models.deletion.CASCADE, to='tasks.task', unique=True),
        ),
    ]
