# Generated by Django 3.2.13 on 2022-08-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_control_weights'),
        ('weak_supervision', '0015_spacymodel_spacymodelresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacyModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='label', max_length=60, null=True)),
                ('coverage', models.FloatField(blank=True, default=0.0, null=True)),
                ('conflicts', models.FloatField(blank=True, default=0.0, null=True)),
                ('overlaps', models.FloatField(blank=True, default=0.0, null=True)),
                ('precision', models.FloatField(blank=True, default=0.0, null=True)),
                ('recall', models.FloatField(blank=True, default=0.0, null=True)),
                ('f1_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('results', models.IntegerField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time a metric was calculated', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time a metric was updated', verbose_name='updated at')),
                ('model', models.ForeignKey(help_text='ner model ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='weak_supervision.spacymodel')),
                ('project', models.ForeignKey(help_text='Project ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='spacymodelmetric',
            constraint=models.UniqueConstraint(fields=('model', 'label'), name='ner-model-label'),
        ),
    ]
