# Generated by Django 3.2.13 on 2022-07-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0016_alter_datadoc_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregate_result',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='aggregate_result',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='aggregate_result',
            name='model_type',
        ),
        migrations.AddField(
            model_name='aggregate_result',
            name='model_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weak_supervision.aggregation_model'),
        ),
        migrations.AddField(
            model_name='aggregate_result',
            name='result',
            field=models.TextField(help_text='annotation results', null=True),
        ),
        migrations.AddField(
            model_name='aggregation_model',
            name='labels',
            field=models.JSONField(default=None, verbose_name='list of labels'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
