# Generated by Django 3.2.13 on 2022-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0017_auto_20220728_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation_model',
            name='disabled_functions',
            field=models.ManyToManyField(help_text='selected labelling functions to ignore for the agg. model', related_name='LFs', to='weak_supervision.labelling_function'),
        ),
    ]
