# Generated by Django 3.2.13 on 2022-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0018_aggregation_model_disabled_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation_model',
            name='conflict',
            field=models.FloatField(default=None, help_text='LF Conflict score', null=True, verbose_name='conflict'),
        ),
        migrations.AddField(
            model_name='aggregation_model',
            name='coverage',
            field=models.FloatField(default=None, help_text='LF Coverage score', null=True, verbose_name='coverage'),
        ),
        migrations.AddField(
            model_name='aggregation_model',
            name='f1_score',
            field=models.FloatField(default=None, help_text='LF F_score score', null=True, verbose_name='f1_score'),
        ),
        migrations.AddField(
            model_name='aggregation_model',
            name='overlap',
            field=models.FloatField(default=None, help_text='LF Overlap score', null=True, verbose_name='overlap'),
        ),
        migrations.AddField(
            model_name='aggregation_model',
            name='precision',
            field=models.FloatField(default=None, help_text='LF Precision score', null=True, verbose_name='precision'),
        ),
        migrations.AddField(
            model_name='aggregation_model',
            name='recall',
            field=models.FloatField(default=None, help_text='LF Recall score', null=True, verbose_name='recall'),
        ),
        migrations.AddField(
            model_name='labelling_function',
            name='conflict',
            field=models.FloatField(default=None, help_text='LF Conflict score', null=True, verbose_name='conflict'),
        ),
        migrations.AddField(
            model_name='labelling_function',
            name='coverage',
            field=models.FloatField(default=None, help_text='LF Coverage score', null=True, verbose_name='coverage'),
        ),
        migrations.AddField(
            model_name='labelling_function',
            name='f1_score',
            field=models.FloatField(default=None, help_text='LF F_score score', null=True, verbose_name='f1_score'),
        ),
        migrations.AddField(
            model_name='labelling_function',
            name='overlap',
            field=models.FloatField(default=None, help_text='LF Overlap score', null=True, verbose_name='overlap'),
        ),
        migrations.AddField(
            model_name='labelling_function',
            name='precision',
            field=models.FloatField(default=None, help_text='LF Precision score', null=True, verbose_name='precision'),
        ),
        migrations.AddField(
            model_name='labelling_function',
            name='recall',
            field=models.FloatField(default=None, help_text='LF Recall score', null=True, verbose_name='recall'),
        ),
    ]
