# Generated by Django 3.2.13 on 2022-08-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20220711_1236'),
        ('weak_supervision', '0019_auto_20220808_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadoc',
            name='task',
            field=models.OneToOneField(help_text='Task ID', on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
