# Generated by Django 3.2.13 on 2022-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0020_alter_datadoc_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregation_model',
            name='disabled_functions',
            field=models.ManyToManyField(help_text='selected labelling functions to ignore for the agg. model', null=True, related_name='LFs', to='weak_supervision.labelling_function'),
        ),
    ]
