# Generated by Django 3.2.13 on 2022-08-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weak_supervision', '0022_alter_aggregation_model_disabled_functions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='function',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='model',
        ),
        migrations.AddField(
            model_name='metric',
            name='function_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='labelling_function',
            name='name',
            field=models.CharField(help_text='name of the Labelling Function', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='conflicts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='overlaps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='results',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
